#!/bin/bash

echo -e "\
Usage: echo -en \"\\\033[\${TextColor}m\" && echo -n FOOBAR && echo -e \"\\\033[00m\"
       echo -en \"\\\033[\${Attribute}m\" && echo -n FOOBAR && echo -e \"\\\033[00m\"
       echo -en \"\\\033[\${TextColor};\${Attribute}m\" && echo FOOBAR && echo -e \"\\\033[00m\"
       echo -en \"\\\033[\${TextColor};\${BackColor}m\" && echo FOOBAR && echo -e \"\\\033[00m\"
       echo -en \"\\\033[\${Attribute};\${BackColor}m\" && echo FOOBAR && echo -e \"\\\033[00m\"
       echo -en \"\\\033[\${TextColor};\${Attribute};\${BackColor}m\" && echo FOOBAR && echo -e \"\\\033[00m\"

###################
#    TextColor    #
###################
\033[30m 30\033[00m(Black)
\033[31m 31\033[00m(Red)
\033[32m 32\033[00m(Green)
\033[33m 33\033[00m(Yellow)
\033[34m 34\033[00m(Blue)
\033[35m 35\033[00m(Magenta)
\033[36m 36\033[00m(Cyan)
\033[37m 37\033[00m(White)

###################
#    Attribute    #
###################
\033[00m 00(None) \033[00m
\033[01m 01(Bold) \033[00m
\033[04m 04(UnderScore) \033[00m
\033[07m 07(Reverse) \033[00m

###################
#    BackColor    #
###################
\033[31;40m 40(Black)   \033[00m
\033[32;41m 41(Red)     \033[00m
\033[33;42m 42(Green)   \033[00m
\033[34;43m 43(Yellow)  \033[00m
\033[35;44m 44(Blue)    \033[00m
\033[36;45m 45(Magenta) \033[00m
\033[37;46m 46(Cyan)    \033[00m
\033[30;47m 47(White)   \033[00m

####################
#     AllCases     #
####################"

textcolors="$(seq 30 37)"
backcolors="$(seq 40 47)"
for textcolor in $textcolors ;do
    echo -e "\033[${textcolor}m ${textcolor} (TextColor:${textcolor}) \033[00m"
done
for textcolor in $textcolors ;do
    echo -e "\033[${textcolor};01m ${textcolor};01 (TextColor:${textcolor},Attribute:01) \033[00m"
done
for textcolor in $textcolors ;do
    for backcolor in $backcolors ;do
        echo -e "\033[${textcolor};${backcolor}m ${textcolor};${backcolor} (TextColor:${textcolor},BackColor:${backcolor}) \033[00m"
    done
done
for textcolor in $textcolors ;do
    for backcolor in $backcolors ;do
        echo -e "\033[${textcolor};01;${backcolor}m ${textcolor};01;${backcolor} (TextColor:${textcolor},Attribute:01,BackColor:${backcolor}) \033[00m"
    done
done
